version: "3.8"

services:
  app:
    build: .
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - "AWS_ENDPOINT_URL=http://localstack:4566"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - "DEBUG=${DEBUG:-0}"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack-data}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
