# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest==8.0.0
        python3 -m pip install ruff==0.2.1
        if [ -f app/requirements.txt ]; then python3 -m pip install -r app/requirements.txt; fi
      shell: bash

    - name: Lint with ruff
      run: |
        ruff format .
      shell: bash


    - name: Test with pytest
      run: |
        pytest . -vv
      shell: bash

